name: 'Generate prelude documentation'

on:
  workflow_dispatch
env:
  node-version: 14.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - run: npm install -g @madlib-lang/madlib

      - run: |
          cd .github/workflows
          madlib install

      # TODO: fix maddoc cli and revert this
      # - run: |
      #     cd .github/workflows
      #     madlib run MadDocCli ../../prelude/__internal__

      - run: |
          cd .github/workflows
          madlib compile --bundle -i madlib_modules/MadDocCli/src/Main.mad -o build/src/maddoc-cli.js
          node build/src/maddoc-cli.js ../../prelude/__internal__

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: docs
          folder: .github/workflows/.docs
